src/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/src/objects/CUSTOMER__c.object
<CustomObject>
    <fields>
        <fullName>ACCOUNT_NUMBER__c</fullName>
        <label>ACCOUNT NUMBER</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CUSTOMERS</relationshipLabel>
        <relationshipName>CUSTOMERS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FAX_NUMBER__c</fullName>
        <label>FAX NUMBER</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PHONE_NUMBER__c</fullName>
        <label>PHONE NUMBER</label>
        <type>Phone</type>
    </fields>
    <label>CUSTOMER</label>
    <nameField>
        <label>CUSTOMER NAME</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CUSTOMERS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/src/objects/User_Story__c.object
<CustomObject>
    <description>User stories are simple descriptions of a feature told from the user&apos;s point of view</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Analysis</fullName>
                    <default>true</default>
                    <label>In Analysis</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>In Development</fullName>
                </value>
                <value>
                    <fullName>Ready For SAT</fullName>
                </value>
                <value>
                    <fullName>In SAT(QA)</fullName>
                </value>
                <value>
                    <fullName>Testing Done</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/src/classes/syncacc.cls
public class syncacc {
    
    public static void afterupdate(map<id,customer__c> cusmap){
        
        list<account> acclist = new list<account>();
        
        set<id> accid = new set<id>();
        
        for(customer__c cus : cusmap.values()){
            
            accid.add(cus.Account__c);
            
        }
        
        map<id,Account> Accmap = new map<id,Account>([select id ,name, AccountNumber, fax, phone from 
                                                      account where id in: accid ]);
        for(customer__c cust : cusmap.values()){
            
            account acc = accmap.get(cust.Account__c);  // important step
            
            acc.Name  = cust.Name ;
            acc.AccountNumber = cust.ACCOUNT_NUMBER__c ;
            acc.Fax =  cust.FAX_NUMBER__c ;
            acc.Phone  = cust.PHONE_NUMBER__c;
            
            acclist.add(acc);
        }
        if(!acclist.isempty()){
            
            update acclist;
        }
    }
}/*
public class approvetask {
    public static void approve(map<id,user_story__c> newmap,map<id,user_story__c> oldmap){
        set<id> usid = new set<id>();
        if(newmap != null){
          for(user_story__c uslist : newmap.values()){
                usid.add(uslist.Id);
          }
            if(oldmap !=  null){
              for(user_story__c usoldlist : oldmap.values()){
                  usid.add(usoldlist.Id);
              }
            //  list<task> tslst = new list<task>(); 
              map<id,task> tskid = new map<id,task>();
              map<id,task> taskmap = new map<id,task>([select id,status,whatid from task where whatid in: usid]);
              for(task tasklist : taskmap.values()){
                  if(tasklist.Status == 'completed'){
                      tskid.put(tasklist.Id,tasklist );
                  } 
              }
               // for(user_story__c uss : newmap.values()){
                     if(uss.status__C == 'approved' && tskid.status == 'completed'){
                           uss.Status__c.adderror('no msg');         
              //  }
                 
              }
             }
          }   
        }
    }          */