src/src/objects/Bug__c.object
<CustomObject>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>Bugs</relationshipLabel>
        <relationshipName>Bugs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Bug</label>
    <nameField>
        <displayFormat>Bug-{0000}</displayFormat>
        <label>Bug Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bugs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/src/objects/User_Story__c.object
<CustomObject>
    <description>User stories are simple descriptions of a feature told from the user&apos;s point of view</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/src/classes/bugrecords.cls
public class bugrecords {
    @AuraEnabled
    public static List <Bug__c> fetchbugrecords(Id recordId) {
        
        list<Bug__c>buglist = [Select Id,name from Bug__c where User_Story__c =: recordId];
        
        return buglist;
        
    }
    
    @AuraEnabled
    public static integer deletebugrecords(List<Bug__c> Deletebug ,string UserStoryid ){
        delete Deletebug;
        integer Bugcount = [select count() from Bug__c where User_Story__c =: UserStoryid ];
        return bugcount;
    }
    
}