src/src/objects/CANDIDATES__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CANDIDATES</relationshipLabel>
        <relationshipName>CANDIDATES</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CANDIDATE</label>
    <nameField>
        <label>CANDIDATES Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CANDIDATES</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>candidate_count__c</fullName>
        <label>candidate count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/src/classes/candidatecountoncontact.cls
public class candidatecountoncontact {
    public static void candidatecount(list<CANDIDATES__c>newcanlist,list<CANDIDATES__c>oldcanlist){
        set<id>conid = new set<id>();
        if(newcanlist != null){
            for(CANDIDATES__c can :newcanlist){
                if(can.contact__c != null){
                    conid.add(can.contact__c);
                }
            }
        }if(oldcanlist != null){
            for(CANDIDATES__c cand : oldcanlist){
                if(cand.contact__c != null){
                    conid.add(cand.Contact__c);
                }
            }
        }  
        
        list<contact> conlist = [select id,candidate_count__c ,(select id from candidates__r) from contact where id in :conid ];
        
        for(contact conta : conlist){
            conta.candidate_count__c = conta.candidates__r.size();
        }
        update conlist;
    }
}