src/src/objects/CUSTOMER__c.object
<CustomObject>
    <fields>
        <fullName>ACCOUNT_NUMBER__c</fullName>
        <label>ACCOUNT NUMBER</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CUSTOMERS</relationshipLabel>
        <relationshipName>CUSTOMERS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FAX_NUMBER__c</fullName>
        <label>FAX NUMBER</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PHONE_NUMBER__c</fullName>
        <label>PHONE NUMBER</label>
        <type>Phone</type>
    </fields>
    <label>CUSTOMER</label>
    <nameField>
        <label>CUSTOMER NAME</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CUSTOMERS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/src/classes/UPDATECUSTOMER.cls
public class UPDATECUSTOMER {
    public static void afterinsert(list<account>acclist){ 
        list<CUSTOMER__c>cuslist = new list<CUSTOMER__c>();
        for(account acc : acclist){
            CUSTOMER__c cus = new CUSTOMER__c();
            cus.Name = acc.Name;
            cus.ACCOUNT_NUMBER__c = acc.AccountNumber;
            cus.FAX_NUMBER__c = acc.Fax;
            cus.PHONE_NUMBER__c = acc.Phone;
            cus.Account__c = acc.Id;
            cuslist.add(cus);
        }
        if(!cuslist.isempty()){
            INSERT cuslist;
        }
    }
    
    public static void afterupdate(map<id,account>accmap){
        
        list<CUSTOMER__c>cuslst = [select id,name,ACCOUNT_NUMBER__c,FAX_NUMBER__c,PHONE_NUMBER__c,Account__c from CUSTOMER__c
                                   where Account__c in : accmap.keyset()];
        
        list<CUSTOMER__c>clist = new list<CUSTOMER__c>();
        
        for(CUSTOMER__c cus : cuslst){
            
            account acc = accmap.get(cus.account__c);
            
            cus.Name = acc.Name;
            cus.ACCOUNT_NUMBER__c = acc.AccountNumber;
            cus.PHONE_NUMBER__c = acc.Phone;
            cus.FAX_NUMBER__c = acc.Fax;
            
            clist.add(cus);
        } if(!clist.isempty()){
            update clist;
        }
    }
    
}