src/src/objects/EM_Day__c.object
<CustomObject>
    <fields>
        <fullName>EM_No_of_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No of Hours</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EM_Time_Sheet__c</fullName>
        <label>Time Sheet</label>
        <referenceTo>EM_Time_Sheet__c</referenceTo>
        <relationshipLabel>Days</relationshipLabel>
        <relationshipName>Days</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EM_Week_Day__c</fullName>
        <label>Week Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SUN</fullName>
                    <default>true</default>
                    <label>SUN</label>
                </value>
                <value>
                    <fullName>MON</fullName>
                </value>
                <value>
                    <fullName>TUE</fullName>
                </value>
                <value>
                    <fullName>WED</fullName>
                </value>
                <value>
                    <fullName>THUR</fullName>
                </value>
                <value>
                    <fullName>FRI</fullName>
                </value>
                <value>
                    <fullName>SAT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Day</label>
    <nameField>
        <displayFormat>Day-{0000}</displayFormat>
        <label>Day Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Days</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/src/objects/EM_Time_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>EM_Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>LMS_Employee__c</referenceTo>
        <relationshipLabel>Time Sheets</relationshipLabel>
        <relationshipName>Time_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EM_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EM_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EM_Total_Hours_Worked__c</fullName>
        <label>Total Hours Worked</label>
        <summarizedField>EM_Day__c.EM_No_of_Hours__c</summarizedField>
        <summaryForeignKey>EM_Day__c.EM_Time_Sheet__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>EM_Week_Days_Count__c</fullName>
        <label>Week Days Count</label>
        <summaryForeignKey>EM_Day__c.EM_Time_Sheet__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Time Sheet</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Time Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/src/objects/LMS_Employee__c.object
<CustomObject>
    <fields>
        <fullName>LMS_Aadhar_Number__c</fullName>
        <label>Aadhar Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LMS_PAN_Number__c</fullName>
        <label>PAN Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LMS_PF_Account_Number__c</fullName>
        <label>PF Account Number</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/src/classes/timesheet_Test.cls
@isTest 
public class timesheet_Test {
    @testSetup  static void testData() {
        
        User user = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            LastName = 'last',
            Email = 'puser000@amamama.com',
            Username = 'puser000@amamama.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US' );
        insert user;
        
        LMS_Employee__c empinfo = new LMS_Employee__c();
        empinfo.Name = 'vinodhkumar';
        empinfo.LMS_Aadhar_Number__c = '673217570919';   
        empinfo.LMS_PAN_Number__c = 'BOCPG6695E';
        empinfo.LMS_PF_Account_Number__c = 'MHBAN00000640000000005';  
        if(empinfo.Name != null){
            insert empinfo;
        }
        
        List<EM_Time_Sheet__c> tymsheet = new List<EM_Time_Sheet__c>();
        EM_Time_Sheet__c tsheet = new EM_Time_Sheet__c();
        tsheet.EM_Start_Date__c = system.today();
        tsheet.EM_End_Date__c = system.today() + 7;
        tsheet.Is_Active__c = true;
        tsheet.EM_Employee__c = empinfo.Id;
        tymsheet.add(tsheet);
        if(tsheet.EM_Employee__c != null){
            insert tymsheet; 
        }
        
        timesheet.dataTableValues dTable = new timesheet.dataTableValues();
        dTable.Isactive = true;
        
        List<EM_Day__c> dLists = new List<EM_Day__c>();
        for(integer j=0; j<7; j++ ){
            EM_Day__c wdays = new EM_Day__c();
            if(j==0){
                wdays.EM_Week_Day__c ='SUN';
            }
            if(j==1){
                wdays.EM_Week_Day__c ='MON';
            }
            if(j==2){
                wdays.EM_Week_Day__c ='TUE';
            }
            if(j==3){
                wdays.EM_Week_Day__c ='WED';
            }
            if(j==4){
                wdays.EM_Week_Day__c ='THUR';
            }
            if(j==5){
                wdays.EM_Week_Day__c ='FRI';
            }
            if(j==6){
                wdays.EM_Week_Day__c ='SAT';
            }            
            wdays.EM_No_of_Hours__c = 2;
            wdays.EM_Time_Sheet__c = tsheet.Id;
            dLists.add(wdays);
        }     
        if(!dLists.isEmpty()){
            insert dLists;
        } 
    }
    
    @isTest 
        static  void validategetDaysWrapper() {        
        test.startTest();
        user user = [select Id, Name from user LIMIT 1];
        EM_Time_Sheet__c Ts = [SELECT Id, Name, EM_Employee__c, EM_Total_Hours_Worked__c, EM_Week_Days_Count__c, EM_Start_Date__c, EM_End_Date__c, Is_Active__c FROM EM_Time_Sheet__c  limit 1];
        List<EM_Day__c> days = [SELECT Id, EM_Time_Sheet__c, EM_No_of_Hours__c, EM_Week_Day__c, Name FROM EM_Day__c 
                                where EM_Time_Sheet__c =: Ts.Id ];
        system.debug(Ts);
        System.assertEquals(true,Ts!=null);    
        timesheet.getDaysWrapper(Ts.id);
        Map<String,integer> WeekdayValues = new  Map<String,integer>();
        timesheet.dataTableValues datavalues = new timesheet.dataTableValues ();        
        for(EM_Day__c testweekdays : days){
            datavalues.weekday =  'Hours Worked';
            datavalues.Isactive = true;
            if(testweekdays.EM_Week_Day__c == 'SUN' && testweekdays.EM_Week_Day__c != NUll){
                datavalues.sunday = Integer.Valueof(testweekdays.EM_No_of_Hours__c);
                system.debug('sunday' + datavalues.sunday);
            }      
            if(testweekdays.EM_Week_Day__c == 'MON' && testweekdays.EM_Week_Day__c != NUll){
                datavalues.monday = Integer.Valueof(testweekdays.EM_No_of_Hours__c);
                system.debug('monday' + datavalues.monday);
            }
            if(testweekdays.EM_Week_Day__c == 'TUE' && testweekdays.EM_Week_Day__c != NUll){
                datavalues.tuesday = Integer.Valueof(testweekdays.EM_No_of_Hours__c);
                system.debug('tuesday' + datavalues.tuesday);
            }
            if(testweekdays.EM_Week_Day__c == 'WED' && testweekdays.EM_Week_Day__c != NUll){
                datavalues.wednesday = Integer.Valueof(testweekdays.EM_No_of_Hours__c);
                system.debug('wednesday' + datavalues.wednesday);
            }
            if(testweekdays.EM_Week_Day__c == 'THUR' && testweekdays.EM_Week_Day__c != NUll){
                datavalues.thursday = Integer.Valueof(testweekdays.EM_No_of_Hours__c);
                system.debug('thursday' + datavalues.thursday);
            }
            if(testweekdays.EM_Week_Day__c == 'FRI' && testweekdays.EM_Week_Day__c != NUll){
                datavalues.friday = Integer.Valueof(testweekdays.EM_No_of_Hours__c);
                system.debug('friday' + datavalues.friday);
            }
            if(testweekdays.EM_Week_Day__c == 'SAT' && testweekdays.EM_Week_Day__c != NUll){
                datavalues.saturday = Integer.Valueof(testweekdays.EM_No_of_Hours__c);
                system.debug('saturday' + datavalues.saturday);
            }  
        }
        datavalues.total = datavalues.sunday + datavalues.monday + datavalues.tuesday + datavalues.wednesday + datavalues.thursday + datavalues.friday + datavalues.saturday;  
        system.debug('total' + datavalues.total);                
        timesheet.wrapperObj wrapperdata = new timesheet.wrapperObj(); 
        wrapperdata.userInfo = user;
        wrapperdata.daterange = Ts;
        wrapperdata.recordId = Ts.Id;
        wrapperdata.dataTableValues = datavalues; 
        String myJSON = JSON.serializePretty(wrapperdata);
        timesheet.updateTimeSheet(myJSON, wrapperdata.recordId); 
}
}