src/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>date_of_join__c</fullName>
        <label>date of join</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>gender__c</fullName>
        <label>gender</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>male</fullName>
                </value>
                <value>
                    <fullName>female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/src/classes/leadtriggertest.cls
@istest
private class leadtriggertest {
    static testmethod void testleadtrigger(){       
        lead ld = new lead();
        ld.Salutation = 'mr';
        ld.LastName = 'testing method';
        ld.Company = 'swhizz tesch';
        ld.Phone = '2584103697';
        ld.gender__c = 'male';
        ld.Industry = 'banking';
        ld.Industry = 'agriculture';
            ld.Industry = 'biotechnology';
            ld.Industry = 'communications';
            ld.Industry = 'apparel';
       
        ld.date_of_join__c = system.today();
     ld.State = 'a.p';
     ld.City = 'vijaywada';
     ld.PostalCode = '500021';
     ld.Country = 'india';
     ld.Street = 'sports complex';
        insert ld;
    }
}