src/src/objects/Question_Master__c.object
<CustomObject>
    <fields>
        <fullName>Question_Text__c</fullName>
        <label>Question Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Radio</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Text Area</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Question Master</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/src/objects/Responses__c.object
<CustomObject>
    <fields>
        <fullName>Answer_Text__c</fullName>
        <label>Answer Text</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Master__c</fullName>
        <label>Question Master</label>
        <referenceTo>Question_Master__c</referenceTo>
        <relationshipLabel>Responses</relationshipLabel>
        <relationshipName>Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sorting_Number__c</fullName>
        <label>Sorting Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Responses</label>
    <nameField>
        <displayFormat>RN-{0000}</displayFormat>
        <label>Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/src/classes/ContactQuestionAssesmentCntrl.cls
public class ContactQuestionAssesmentCntrl {
    @AuraEnabled 
    public static  Map<string,questionwrapperclass> getResponse(){
        Map<string,questionwrapperclass> questionFinalWrapper=new Map<string,questionwrapperclass>();
        List<questionwrapperclass> objlist = new List<questionwrapperclass>();  
        Map<string,List<string>> mapResponseEntity = new Map<string,List<string>>();  
        List<Responses__c> resplist =  [SELECT Id, Name, Question_Master__c, Answer_Text__c, Sorting_Number__c, Question_Master__r.Question_Type__c  FROM Responses__c ORDER BY Sorting_Number__c];
        Map<Id,Question_Master__c> quesMap = new Map<Id,Question_Master__c>([SELECT Id,Name, Question_Text__c,Question_Type__c FROM Question_Master__c]);       
        Map<Id,List<responsewrapperclass>> questionResponseMap=new Map<Id,List<responsewrapperclass>>();        
        responsewrapperclass respObj;
        for(Responses__c eachResponse :resplist){ 
            respObj = new responsewrapperclass();
            respObj.Answertext=eachResponse.Answer_Text__c;
            respObj.responseId=eachResponse.Id;
            respObj.questionId=eachResponse.Question_Master__c;
            respObj.SortingNumber=Integer.valueof(eachResponse.Sorting_Number__c);            
            if(mapResponseEntity.containskey(eachResponse.Question_Master__c)){                 
                mapResponseEntity.get(eachResponse.Question_Master__c).add(eachResponse.Answer_Text__c);               
            }else if(!mapResponseEntity.containskey(eachResponse.Question_Master__c)){                 
                mapResponseEntity.put(eachResponse.Question_Master__c,new List<string>{eachResponse.Answer_Text__c});
            }
            if(!questionResponseMap.containskey(eachResponse.Question_Master__c)){                 
                questionResponseMap.put(eachResponse.Question_Master__c,new List<responsewrapperclass>{respObj});               
            }else if(questionResponseMap.containskey(eachResponse.Question_Master__c)){                 
                questionResponseMap.get(eachResponse.Question_Master__c).add(respObj);
            }
        }
        questionwrapperclass queObj;
        for(Question_Master__c eachQuestion : quesMap.values()){    
            queObj =  new questionwrapperclass();
            queObj.questionText = eachQuestion.Question_Text__c;
            queObj.questionId = eachQuestion.Id;
            queObj.questionType = eachQuestion.Question_Type__c; 
            queObj.selectedResponse='';
            if(questionResponseMap.containsKey(eachQuestion.Id)){
                queObj.responseWrapper =questionResponseMap.get(eachQuestion.Id);                   
            }else{
                queObj.responseWrapper = new List<responsewrapperclass>();  
            }
            queObj.responseMap= questionResponseMap;
            queObj.responseObject='';
            questionFinalWrapper.put(eachQuestion.Question_Text__c,queObj);
        }           
        return questionFinalWrapper;           
    }    
    public class questionwrapperclass{
        @AuraEnabled public string questionText{get;set;}
        @AuraEnabled public string questionType{get;set;}
        @AuraEnabled public string questionId{get;set;}
        @AuraEnabled public Object responseObject{get;set;}
        @AuraEnabled public String selectedResponse{get;set;}
        @AuraEnabled public Map<Id,List<responsewrapperclass>> responseMap{get;set;}
        @AuraEnabled public List<responsewrapperclass> responseWrapper{get;set;}       
    }  
    public class responsewrapperclass{
        @AuraEnabled public string Answertext{get;set;}
        @AuraEnabled public string responseId{get;set;}
        @AuraEnabled public string questionId{get;set;}
        @AuraEnabled public Integer SortingNumber{get;set;}
    } 
    @AuraEnabled 
    public static void updateContact(String details){
        
    }
}