src/src/objects/Sprint__c.object
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/src/objects/User_Story__c.object
<CustomObject>
    <description>User stories are simple descriptions of a feature told from the user&apos;s point of view</description>
    <fields>
        <fullName>Acceptance_Criteria__c</fullName>
        <label>Acceptance Criteria</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>As_a__c</fullName>
        <label>As a</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Assigned_BA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned BA</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Stories1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assigned_Date__c</fullName>
        <description>Which date the record will be assigned.</description>
        <label>Assigned Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Assigned_Developer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Developer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assigned_QA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned QA</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Stories2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Objective__c</fullName>
        <label>Business Objective</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>the date on which something falls due, especially the payment of a bill.</description>
        <label>Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Estimated_Hours__c</fullName>
        <label>Estimated Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>I_want_to__c</fullName>
        <label>I want to</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Analysis</fullName>
                    <default>true</default>
                    <label>In Analysis</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>In Development</fullName>
                </value>
                <value>
                    <fullName>Ready For SAT</fullName>
                </value>
                <value>
                    <fullName>In SAT(QA)</fullName>
                </value>
                <value>
                    <fullName>Testing Done</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <label>Story Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <label>Sub-Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Doing</fullName>
                </value>
                <value>
                    <fullName>Done</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wire_Frames__c</fullName>
        <label>Wire Frames</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/src/classes/userstoryrecordapexctrl.cls
public class userstoryrecordapexctrl {
    @AuraEnabled 
    public static string result(User_Story__c usstory){
        if(usstory.id != null){
            update usstory;
        }else{
            insert usstory;
        }  
        return usstory.id;
    }
    
    @AuraEnabled //get Status Picklist Values        
    public static userpickList getStatus(){
        
        Map<String, String> statusoptions = new Map<String, String>();
        Map<String, String> substatusoptions = new Map<String, String>();
        Map<String, list<string>> depvalues = new Map<String, list<string>>();
        List<string> substatus = new List<string>();        	
        
        //get Status Field Describe
        Schema.DescribeFieldResult statusfieldResult = User_Story__c.Status__c.getDescribe();
        Schema.DescribeFieldResult substatusfieldResult = User_Story__c.Sub_Status__c.getDescribe();
        
        //get Status and sub status Picklist Values
        List<Schema.PicklistEntry> statusList = statusfieldResult.getPicklistValues();
        List<Schema.PicklistEntry> substatusList = substatusfieldResult.getPicklistValues();
        
        for(Schema.PicklistEntry psub: substatusList){
            //Put sub status Picklist Value & Label in Map
            substatusoptions.put(psub.getValue(),psub.getLabel());
            substatus.add(psub.getValue());   
        }      
        
        for(Schema.PicklistEntry pstatus: statusList){
            //Put Picklist Value & Label in Map
            statusoptions.put(pstatus.getValue(),pstatus.getLabel());
            if(pstatus.getValue() == 'IN SAT(QA)' || pstatus.getValue() == 'In development'){
                depvalues.put(pstatus.getValue(),substatus); 
            }        
        }          
        
        userpickList wrpcls = new userpickList(); 
        wrpcls.status = statusoptions;
        wrpcls.substatus = substatusoptions;
        wrpcls.depvalues =depvalues;
        return wrpcls;
    }
    public class userpickList{
        @AuraEnabled public Map<String,String> status{get;set;}
        @AuraEnabled public Map<String,String> substatus{get;set;}
        @AuraEnabled public Map<String,list<String>> depvalues{get;set;}
    }
    
    @AuraEnabled
    public static User_Story__c  getuserstoryrecord(string editedrecordid) {
        User_Story__c usrecord = [SELECT Id, Acceptance_Criteria__c,As_a__c,Assigned_BA__c, Assigned_Date__c,Assigned_Developer__c,
                                  Assigned_QA__c,Business_Objective__c,CreatedById,Description__c,Due_Date__c,Estimated_Hours__c,
                                  I_want_to__c,LastModifiedById,Sprint__c,Status__c,Story_Points__c,Sub_Status__c,Name,Wire_Frames__c FROM User_Story__c where Id =: editedrecordid];
        
        system.debug('usrecord');
        return usrecord;          
    }
    @AuraEnabled 
    public static string updatedresult(User_Story__c upusrecord){
        system.debug('user'+upusrecord);
        if(upusrecord.id != null){
            update upusrecord;
        }else{
            insert upusrecord;
        }  
        return upusrecord.id;
        }
    }