src/src/objects/Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Project Admin</fullName>
                </value>
                <value>
                    <fullName>Team Member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/src/classes/teammemberclass.cls
public class teammemberclass {
@AuraEnabled 
    public static void results(Team_Member__c member){
        insert member;
    }
    @AuraEnabled 
    public static List<teamwrapperclass> getTeammembers(){
        List<Team_Member__c> teamlist = [Select Id,Role__c,User__r.Name from Team_Member__c ]; 
        
        List<teamwrapperclass> objlist = new List<teamwrapperclass>();
        
        for(Team_Member__c tmember : teamlist){
            teamwrapperclass obj = new teamwrapperclass();
           
            obj.role = tmember.Role__c;
            obj.name = tmember.User__r.Name;
            obj.recordId = tmember.Id;
            objlist.add(obj);
        }
        return objlist;
    }
    public class teamwrapperclass{
         @AuraEnabled public string role{get;set;}
         @AuraEnabled public string name{get;set;}
         @AuraEnabled public string recordId{get;set;}
    }  
    @auraEnabled 
    public static void deleteteammember(string teamrecordId ){
         Team_Member__c deleterecord = [SELECT Id,User__r.Name, Role__c FROM Team_Member__c where Id =: teamrecordId];
        delete deleterecord;
        
    }
  }