src/src/objects/User_Story__c.object
<CustomObject>
    <description>User stories are simple descriptions of a feature told from the user&apos;s point of view</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Analysis</fullName>
                    <default>true</default>
                    <label>In Analysis</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>In Development</fullName>
                </value>
                <value>
                    <fullName>Ready For SAT</fullName>
                </value>
                <value>
                    <fullName>In SAT(QA)</fullName>
                </value>
                <value>
                    <fullName>Testing Done</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/src/classes/approvetask.cls
public class approvetask {
     public static void approve(list<user_story__c> userlist){
         map<id,user_story__c> usid = new map<id,user_story__c>();
            for(user_story__c uslist : userlist){
                if(uslist.Status__c == 'approved'){
                   usid.put(uslist.Id,uslist); 
                  }
               }       
         map<id,task> taskmap = new map<id,task>([select id,status,whatid from task where whatid in : usid.keyset()]);
            for(task tasklist : taskmap.values()){
                 if(tasklist.Status != 'completed' ){
                    usid.values().status__c.adderror('You Can not approve a user story while the task status is opened');                             
                    }                    
                 } 
        }
    }