src/src/objects/User_Story__c.object
<CustomObject>
    <description>User stories are simple descriptions of a feature told from the user&apos;s point of view</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Analysis</fullName>
                    <default>true</default>
                    <label>In Analysis</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>In Development</fullName>
                </value>
                <value>
                    <fullName>Ready For SAT</fullName>
                </value>
                <value>
                    <fullName>In SAT(QA)</fullName>
                </value>
                <value>
                    <fullName>Testing Done</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Story Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/src/classes/taskapproved.cls
public class taskapproved {
    public static void Validationruleforuser(list<User_Story__c> USnewList ){
   /*     Map<ID,User_Story__c> UserIDs = new Map<ID,User_Story__c>();
        for(User_Story__c UsLst :USnewList){
            UserIDs.put(UsLst.ID,UsLst);
        }
        
        list<task> Tasklst =[select id,status,whatid from task where whatid IN:UserIDs.keyset()];
        for(task tklst:Tasklst){
            if(UserIDs.get(tklst.whatId).Status__c == 'Approved' && Tklst.Status != 'Completed' ){
            UserIDs.Values().Status__c.adderror('you cannot approve a user story while the task are open');
            }
        } */
    }
}